// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoe4P8f6LCs6jX4f0Ck__k6zyhakbw18o',
    appId: '1:557237544811:web:52d6610b8a5dc1b8d84e2e',
    messagingSenderId: '557237544811',
    projectId: 'linked-in-clone1-6b851',
    authDomain: 'linked-in-clone1-6b851.firebaseapp.com',
    storageBucket: 'linked-in-clone1-6b851.appspot.com',
    measurementId: 'G-Z3HW54556G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rIcYaABsa3NAB4cXjwATd2gvwA4zz_Q',
    appId: '1:557237544811:android:4f29ccc2ef600ec5d84e2e',
    messagingSenderId: '557237544811',
    projectId: 'linked-in-clone1-6b851',
    storageBucket: 'linked-in-clone1-6b851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfDYfx_jJA5Ex2UKQn82yuw6F0Oq1mbk',
    appId: '1:557237544811:ios:b63f92da6a280a65d84e2e',
    messagingSenderId: '557237544811',
    projectId: 'linked-in-clone1-6b851',
    storageBucket: 'linked-in-clone1-6b851.appspot.com',
    iosBundleId: 'com.example.linkedinMobileUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtfDYfx_jJA5Ex2UKQn82yuw6F0Oq1mbk',
    appId: '1:557237544811:ios:1b8493cc3eb7a0dfd84e2e',
    messagingSenderId: '557237544811',
    projectId: 'linked-in-clone1-6b851',
    storageBucket: 'linked-in-clone1-6b851.appspot.com',
    iosBundleId: 'com.example.linkedinMobileUi.RunnerTests',
  );
}
